models/Users.php
<?php

namespace app\models;

use app\components\events\UserActiveEvent;
use app\components\events\UserRegistrationEvent;
use app\components\helpers\UserHelper;
use Yii;
use yii\helpers\ArrayHelper;
use yii\web\IdentityInterface;


/**
 * This is the model class for table "users".
 *
 * @property string $id
 * @property string $email
 * @property string $username
 * @property string $password
 * @property integer $active
 * @property integer $date_reg
 * @property string $auth_key
 * @property string $access_token
 */
class Users extends \yii\db\ActiveRecord implements IdentityInterface
{

    const EVENT_USER_REG    = 'user_registration';
    const EVENT_USER_ACTIVE = 'user_active';

    public $roles;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'users';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['email', 'username', 'password', 'date_reg'], 'required'],
            [['active', 'date_reg'], 'integer'],
            [['email', 'username', 'password'], 'string', 'max' => 255],
            [['auth_key', 'access_token'], 'string', 'max' => 128],
            ['password', 'string', 'min' => 5],
            ['email', 'email'],
            [['email', 'username'], 'unique'],
            ['roles', 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id'       => 'ID',
            'email'    => 'Email',
            'username' => 'Username',
            'password' => 'Password',
            'active'   => 'Active',
            'date_reg' => 'Reg Date',
            'roles'    => 'Roles',
        ];
    }

    //region Identity
    /**
     * Finds an identity by the given ID.
     * @param string|integer $id the ID to be looked for
     * @return IdentityInterface the identity object that matches the given ID.
     * Null should be returned if such an identity cannot be found
     * or the identity is not in an active state (disabled, deleted, etc.)
     */
    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    /**
     * Finds an identity by the given token.
     * @param mixed $token the token to be looked for
     * @param mixed $type the type of the token. The value of this parameter depends on the implementation.
     * For example, [[\yii\filters\auth\HttpBearerAuth]] will set this parameter to be `yii\filters\auth\HttpBearerAuth`.
     * @return IdentityInterface the identity object that matches the given token.
     * Null should be returned if such an identity cannot be found
     * or the identity is not in an active state (disabled, deleted, etc.)
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        return static::findOne(['access_token' => $token]);
    }

    /**
     * Returns an ID that can uniquely identify a user identity.
     * @return string|integer an ID that uniquely identifies a user identity.
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Returns a key that can be used to check the validity of a given identity ID.
     *
     * The key should be unique for each individual user, and should be persistent
     * so that it can be used to check the validity of the user identity.
     *
     * The space of such keys should be big enough to defeat potential identity attacks.
     *
     * This is required if [[User::enableAutoLogin]] is enabled.
     * @return string a key that is used to check the validity of a given identity ID.
     * @see validateAuthKey()
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * Validates the given auth key.
     *
     * This is required if [[User::enableAutoLogin]] is enabled.
     * @param string $authKey the given auth key
     * @return boolean whether the given auth key is valid.
     * @see getAuthKey()
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }
    //endregion

    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            if ($this->isNewRecord) {
                $this->auth_key     = \Yii::$app->security->generateRandomString();
                $this->access_token = \Yii::$app->security->generateRandomString();
            }
            return true;
        }
        return false;
    }

    public function afterSave($insert, $changedAttributes)
    {
        if(!empty($this->roles)) {
            if(!is_array($this->roles)) {
                $this->roles = (array)$this->roles;
            }

            Yii::$app->authManager->revokeAll($this->id);

            foreach($this->roles as $_role) {
                $userRole = Yii::$app->authManager->getRole($_role);
                Yii::$app->authManager->assign($userRole, $this->id);
            }
        }

        parent::afterSave($insert, $changedAttributes);
    }

    public static function getUserRoles($id) {
        $roles = \Yii::$app->authManager->getRolesByUser($id);

        //echo '<pre>'; print_r($roles); echo '</pre>';

        return ArrayHelper::map($roles, 'name', 'name');
    }

    public function validatePassword($password) {
        return Yii::$app->getSecurity()->validatePassword($password, $this->password);
    }

    /**
     * @param $username
     * @return Users|null
     */
    public static function findByUsername($username) {
        return static::findOne(['username' => $username]);
    }

    public static function getUsers() {
        return Users::find()->all();
    }

    public static function createUser($username, $password, $email, $roles = []) {
        $user = new Users();
        $user->email = $email;
        $user->username = $username;
        $user->password = Yii::$app->getSecurity()->generatePasswordHash($password);
        $user->date_reg = time();

        $ar_count = static::find()->count();


        $user->roles = empty($roles) ? [UserHelper::ROLE_USER] : $roles;

        if($ar_count == 0) {
            $user->roles = UserHelper::ROLE_ADMIN;
        }


        if($user->save()) {
            $event = new UserRegistrationEvent;
            $event->username = $username;
            $event->password = $password;
            $event->email    = $email;

            $user->trigger(self::EVENT_USER_REG, $event);

            return true;
        }

        return false;
    }

    public static function changeActiveState($user_id, $active) {
        $user = Users::findOne(['id' => $user_id]);

        if(empty($user)) {
            return false;
        }

        $user->active = intval($active);

        if($user->save()) {
            $event = new UserActiveEvent;

            $event->active   = $user->active;
            $event->username = $user->username;
            $event->email    = $user->email;

            $user->trigger(self::EVENT_USER_ACTIVE, $event);

            return true;
        }

        return false;
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\components\helpers\FlashHelper;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\helpers\Json;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm(['scenario' => 'login']);
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(['/notifications/logs']);
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionRegister() {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm(['scenario' => 'register']);

        if ($model->load(Yii::$app->request->post()) && $model->register()) {
            FlashHelper::setFlashSuccess('New user was successfully registered');
            return $this->goBack();
        }

        return $this->render('register', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    public function actionCreateUrl() {
        if(!Yii::$app->request->isAjax) {
            throw new NotFoundHttpException('The requested page does not exist.');
        }

        $post = Yii::$app->request->post('RouteParams');

        if(empty($post) or !isset($post['route']) or !isset($post['params'])) {
            throw new BadRequestHttpException('Bad Request');
        }

        $result = [
            'success' => true,
            'url' => Url::to(array_merge((array)$post['route'], $post['params'])),
        ];

        echo Json::encode($result);
    }

    public function actionAbout()
    {
        return $this->render('about');
    }
}

controllers/UsersController.php
<?php

namespace app\controllers;

use app\components\helpers\FlashHelper;
use app\components\helpers\UserHelper;
use Yii;
use app\models\Users;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\helpers\Json;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UsersController implements the CRUD actions for Users model.
 */
class UsersController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'only'  => ['index', 'view', 'create', 'update', 'delete', 'changeActive', 'changeRole'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => [UserHelper::ROLE_ADMIN],
                    ]
                ],

            ],
        ];
    }

    /**
     * Lists all Users models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Users::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Users model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Users model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Users();

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            Users::createUser($model->username, $model->password, $model->email, $model->roles);

            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Users model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        $active_state = $model->active;

        $prev_password = $model->password;

        $model->roles = Users::getUserRoles($id);

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {

            if($prev_password != $model->password) {
                $model->password = Yii::$app->getSecurity()->generatePasswordHash($model->password);
            }

            $model->save();

            if($model->active != $active_state) {
                Users::changeActiveState($id, $model->active);
            }

            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Users model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionChangeActive($id) {
        $this->findModel($id);

        $active = \Yii::$app->request->post('active');

        $success = Users::changeActiveState($id, $active);

        if(!Yii::$app->request->isAjax) {
            if($success) {
                FlashHelper::setFlashSuccess('User active state successfully changed');
            } else {
                FlashHelper::setFlashError('Occurred some problems in changing user active state');
            }

            $this->redirect(Yii::$app->request->getReferrer());
        } else {
            $response = [ 'success' => $success, 'active' => $active ];
            echo Json::encode($response);
        }
    }

    public function actionChangeRole($id) {
        $this->findModel($id);

        $role = Yii::$app->request->post('role');

        Yii::$app->authManager->revokeAll($id);


        $role = Yii::$app->authManager->getRole($role);
        Yii::$app->authManager->assign($role, $id);
    }

    /**
     * Finds the Users model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Users the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/users/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Users */
/* @var $form yii\widgets\ActiveForm */

$all_roles = \app\components\helpers\UserHelper::getRoles();

$listData = array_combine($all_roles, $all_roles);
?>

<div class="users-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'active')->checkbox() ?>

    <?= $form->field($model, 'roles')->listBox($listData, ['multiple' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/users/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Users */

$this->title = 'Create Users';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/users/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Users';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Users', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'email:email',
            'username',
            //'password',
            [
                'attribute' => 'active',
                'value'     => function($data) {
                    return $data->active;
                },
                'contentOptions'   => ['class' => 'active-state'],
            ],
            [
                'attribute' => 'roles',
                'value'     => function($data) {
                    return implode(',', \app\models\Users::getUserRoles($data->id));
                }
            ],
            [
                'attribute' => 'date_reg',
                'value' => function($data) {
                    return date('Y-m-d H:i:s', $data->date_reg);
                }
            ],

            ['class' => 'yii\grid\ActionColumn', 'template' => '{update}{delete}'],
        ],
    ]); ?>
</div>

<script type="text/javascript">
    $(function() {
        $('.active-state').on('click', changeActiveState);


    });

    function changeActiveState() {

        var $obj = $(this);

        var active = $obj.text();
        var id     = $obj.parents('tr').data('key');

        var new_active = active == '1' ? '0' : '1';

        var data_active = { 'active': new_active };

        var data_route = { 'RouteParams': { 'route': '/users/change-active', 'params': { 'id': id } } };


        $.post(
            '<?= \yii\helpers\Url::to(['/site/create-url']); ?>',
            data_route,
            function(resp) {
                if(resp.success) {
                    sendRequest(resp.url, data_active, $obj);
                }
            },
            'json'
        );
    }

    function sendRequest(url, data, $obj) {

        $.post(
            url,
            data,
            function(resp) {
                var n = Noty('id');

                if(resp.success) {
                    $obj.text(resp.active);

                    $.noty.setText(n.options.id, 'Active state successfully changed');
                    $.noty.setType(n.options.id, 'success');
                } else {
                    $.noty.setText(n.options.id, 'Occurred some error in request');
                    $.noty.setType(n.options.id, 'error');
                }
            },
            'json'
        ).fail(function() {
                var n = Noty('id');

                $.noty.setText(n.options.id, 'Occurred some error in request');
                $.noty.setType(n.options.id, 'error');
            });
    }
</script>

views/users/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Users */

$this->title = 'Update Users: ' . $model->username;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="users-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/users/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Users */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'email:email',
            'username',
            'password',
            'active',
            'date_reg',
        ],
    ]) ?>

</div>